# Generated by Django 6.0.5 on 2026-05-15 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bark',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='bark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barks', to=settings.AUTH_USER_MODEL),
        ),
    ]
