# Generated by Django 6.0.5 on 2026-05-17 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barks', '0002_alter_bark_options_alter_bark_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bark',
            name='content',
            field=models.CharField(max_length=280),
        ),
    ]
